package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AOrganization generated by hbm2java
 */
@Entity
@Table(name = "a_organization", schema = "public")
public class AOrganization implements java.io.Serializable {

  private long orgId;
  private long parentId;
  private String orgName;
  private Boolean isDeleted;
  private String orgCoding;
  private String postalCode;
  private String authOrgName;
  private String authPeople;
  private String authPhone;
  private String fbfName;
  private String fbfLegalPerson;
  private String fbfPhone;
  private String fbfAddress;
  private String orgMember;
  private Short regionType;
  private Short orgLevel;

  public AOrganization() {
  }

  public AOrganization(long orgId) {
    this.orgId = orgId;
  }

  public AOrganization(long orgId, long parentId, String orgName, Boolean isDeleted, String orgCoding, String postalCode, String authOrgName, String authPeople, String authPhone, String fbfName, String fbfLegalPerson, String fbfPhone, String fbfAddress, String orgMember, Short regionType, Short orgLevel) {
    this.orgId = orgId;
    this.parentId = parentId;
    this.orgName = orgName;
    this.isDeleted = isDeleted;
    this.orgCoding = orgCoding;
    this.postalCode = postalCode;
    this.authOrgName = authOrgName;
    this.authPeople = authPeople;
    this.authPhone = authPhone;
    this.fbfName = fbfName;
    this.fbfLegalPerson = fbfLegalPerson;
    this.fbfPhone = fbfPhone;
    this.fbfAddress = fbfAddress;
    this.orgMember = orgMember;
    this.regionType = regionType;
    this.orgLevel = orgLevel;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "org_seq")
  @SequenceGenerator(name = "org_seq", sequenceName = "org_id_seq")
  @Column(name = "org_id", unique = true, nullable = false)
  public long getOrgId() {
    return this.orgId;
  }

  public void setOrgId(long orgId) {
    this.orgId = orgId;
  }

  @Column(name = "org_name")
  public String getOrgName() {
    return this.orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  @Column(name = "is_deleted")
  public Boolean getIsDeleted() {
    return this.isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  @Column(name = "org_coding")
  public String getOrgCoding() {
    return this.orgCoding;
  }

  public void setOrgCoding(String orgCoding) {
    this.orgCoding = orgCoding;
  }

  @Column(name = "postal_code")
  public String getPostalCode() {
    return this.postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  @Column(name = "auth_org_name")
  public String getAuthOrgName() {
    return this.authOrgName;
  }

  public void setAuthOrgName(String authOrgName) {
    this.authOrgName = authOrgName;
  }

  @Column(name = "auth_people")
  public String getAuthPeople() {
    return this.authPeople;
  }

  public void setAuthPeople(String authPeople) {
    this.authPeople = authPeople;
  }

  @Column(name = "auth_phone")
  public String getAuthPhone() {
    return this.authPhone;
  }

  public void setAuthPhone(String authPhone) {
    this.authPhone = authPhone;
  }

  @Column(name = "fbf_name")
  public String getFbfName() {
    return this.fbfName;
  }

  public void setFbfName(String fbfName) {
    this.fbfName = fbfName;
  }

  @Column(name = "fbf_legal_person")
  public String getFbfLegalPerson() {
    return this.fbfLegalPerson;
  }

  public void setFbfLegalPerson(String fbfLegalPerson) {
    this.fbfLegalPerson = fbfLegalPerson;
  }

  @Column(name = "fbf_phone")
  public String getFbfPhone() {
    return this.fbfPhone;
  }

  public void setFbfPhone(String fbfPhone) {
    this.fbfPhone = fbfPhone;
  }

  @Column(name = "fbf_address")
  public String getFbfAddress() {
    return this.fbfAddress;
  }

  public void setFbfAddress(String fbfAddress) {
    this.fbfAddress = fbfAddress;
  }

  @Column(name = "org_member")
  public String getOrgMember() {
    return this.orgMember;
  }

  public void setOrgMember(String orgMember) {
    this.orgMember = orgMember;
  }

  @Column(name = "region_type")
  public Short getRegionType() {
    return this.regionType;
  }

  public void setRegionType(Short regionType) {
    this.regionType = regionType;
  }

  @Column(name = "org_level")
  public Short getOrgLevel() {
    return this.orgLevel;
  }

  public void setOrgLevel(Short orgLevel) {
    this.orgLevel = orgLevel;
  }

  /**
   * @return the parentId
   */
  @Column(name = "parent_id")
  public long getParentId() {
    return parentId;
  }

  /**
   * @param parentId the parentId to set
   */
  public void setParentId(long parentId) {
    this.parentId = parentId;
  }
}
