package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AUser generated by hbm2java
 */
@Entity
@Table(name = "a_user", schema = "public"
)
public class AUser2 implements java.io.Serializable {

  private int id;
  private String ip;
  private String qq;
  private String addr;
  private String email;
  private String name;
  private String password;
  private String phone;
  private Date regDate;
  private Boolean sex;
  private Boolean canDelete;
  private int orgId;
  private String orgName;

  public AUser2() {
  }

  public AUser2(int id) {
    this.id = id;
  }

  public AUser2(int id, String ip, String qq, String addr, String email, String name, String password, String phone, Date regDate, Boolean sex, Boolean canDelete, int orgId, String orgName) {
    this.id = id;
    this.ip = ip;
    this.qq = qq;
    this.addr = addr;
    this.email = email;
    this.name = name;
    this.password = password;
    this.phone = phone;
    this.regDate = regDate;
    this.sex = sex;
    this.canDelete = canDelete;
    this.orgId = orgId;
    this.orgName = orgName;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_seq")
  @SequenceGenerator(name = "user_seq", sequenceName = "user_id_seq", allocationSize = 1)
  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  @Column(name = "ip")
  public String getIp() {
    return this.ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  @Column(name = "qq")
  public String getQq() {
    return this.qq;
  }

  public void setQq(String qq) {
    this.qq = qq;
  }

  @Column(name = "addr")
  public String getAddr() {
    return this.addr;
  }

  public void setAddr(String addr) {
    this.addr = addr;
  }

  @Column(name = "email")
  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  @Column(name = "name")
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "password")
  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  @Column(name = "phone")
  public String getPhone() {
    return this.phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "reg_date", length = 13)
  public Date getRegDate() {
    return this.regDate;
  }

  public void setRegDate(Date regDate) {
    this.regDate = regDate;
  }

  @Column(name = "sex")
  public Boolean getSex() {
    return this.sex;
  }

  public void setSex(Boolean sex) {
    this.sex = sex;
  }

  /**
   * @return the canDelete
   */
  @Column(name = "can_delete")
  public Boolean getCanDelete() {
    return canDelete;
  }

  /**
   * @param canDelete the canDelete to set
   */
  public void setCanDelete(Boolean canDelete) {
    this.canDelete = canDelete;
  }

  /**
   * @return the orgId
   */
  @Column(name = "org_id")
  public int getOrgId() {
    return orgId;
  }

  /**
   * @param orgId the orgId to set
   */
  public void setOrgId(int orgId) {
    this.orgId = orgId;
  }

  /**
   * @return the orgName
   */
  @Column(name = "org_name")
  public String getOrgName() {
    return orgName;
  }

  /**
   * @param orgName the orgName to set
   */
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

}
