package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cbf generated by hbm2java
 */
@Entity
@Table(name = "cbf", schema = "public")
public class Cbf implements java.io.Serializable {

  private long id;
  private long orgId;
  private String cbfbm;
  private Character cbflx;
  private String cbfmc;
  private char  cbfxb;
  private String cbfmz;
  private Character cbfzjlx;
  private String cbfzjhm;
  private String cbfdz;
  private String yzbm;
  private String lxdh;
  private Integer cbfcysl;
  private Date cbfdcrq;
  private String cbfdcy;
  private String cbfdcjs;
  private String gsjs;
  private String gsjsr;
  private Date gsshrq;
  private String gsshr;

  public Cbf() {
  }

  public Cbf(long id) {
    this.id = id;
  }

  public Cbf(long id, String cbfbm, Character cbflx, String cbfmc, char cbfxb, String cbfmz, Character cbfzjlx, String cbfzjhm, String cbfdz, String yzbm, String lxdh, Integer cbfcysl, Date cbfdcrq, String cbfdcy, String cbfdcjs, String gsjs, String gsjsr, Date gsshrq, String gsshr) {
    this.id = id;
    this.cbfbm = cbfbm;
    this.cbflx = cbflx;
    this.cbfmc = cbfmc;
    this.cbfxb = cbfxb;
    this.cbfmz = cbfmz;
    this.cbfzjlx = cbfzjlx;
    this.cbfzjhm = cbfzjhm;
    this.cbfdz = cbfdz;
    this.yzbm = yzbm;
    this.lxdh = lxdh;
    this.cbfcysl = cbfcysl;
    this.cbfdcrq = cbfdcrq;
    this.cbfdcy = cbfdcy;
    this.cbfdcjs = cbfdcjs;
    this.gsjs = gsjs;
    this.gsjsr = gsjsr;
    this.gsshrq = gsshrq;
    this.gsshr = gsshr;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbf_seq")
  @SequenceGenerator(name = "cbf_seq", sequenceName = "cbf_id_seq",allocationSize=1)
  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @Column(name = "cbfbm", length = 18)
  public String getCbfbm() {
    return this.cbfbm;
  }

  public void setCbfbm(String cbfbm) {
    this.cbfbm = cbfbm;
  }

  @Column(name = "cbflx", length = 1)
  public Character getCbflx() {
    return this.cbflx;
  }

  public void setCbflx(Character cbflx) {
    this.cbflx = cbflx;
  }

  @Column(name = "cbfmc", length = 50)
  public String getCbfmc() {
    return this.cbfmc;
  }

  public void setCbfmc(String cbfmc) {
    this.cbfmc = cbfmc;
  }

  @Column(name = "cbfzjlx", length = 1)
  public Character getCbfzjlx() {
    return this.cbfzjlx;
  }

  public void setCbfzjlx(Character cbfzjlx) {
    this.cbfzjlx = cbfzjlx;
  }

  @Column(name = "cbfzjhm", length = 20)
  public String getCbfzjhm() {
    return this.cbfzjhm;
  }

  public void setCbfzjhm(String cbfzjhm) {
    this.cbfzjhm = cbfzjhm;
  }

  @Column(name = "cbfdz", length = 100)
  public String getCbfdz() {
    return this.cbfdz;
  }

  public void setCbfdz(String cbfdz) {
    this.cbfdz = cbfdz;
  }

  @Column(name = "yzbm", length = 6)
  public String getYzbm() {
    return this.yzbm;
  }

  public void setYzbm(String yzbm) {
    this.yzbm = yzbm;
  }

  @Column(name = "lxdh", length = 20)
  public String getLxdh() {
    return this.lxdh;
  }

  public void setLxdh(String lxdh) {
    this.lxdh = lxdh;
  }

  @Column(name = "cbfcysl")
  public Integer getCbfcysl() {
    return this.cbfcysl;
  }

  public void setCbfcysl(Integer cbfcysl) {
    this.cbfcysl = cbfcysl;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "cbfdcrq", length = 13)
  public Date getCbfdcrq() {
    return this.cbfdcrq;
  }

  public void setCbfdcrq(Date cbfdcrq) {
    this.cbfdcrq = cbfdcrq;
  }

  @Column(name = "cbfdcy", length = 50)
  public String getCbfdcy() {
    return this.cbfdcy;
  }

  public void setCbfdcy(String cbfdcy) {
    this.cbfdcy = cbfdcy;
  }

  @Column(name = "cbfdcjs", length = 300)
  public String getCbfdcjs() {
    return this.cbfdcjs;
  }

  public void setCbfdcjs(String cbfdcjs) {
    this.cbfdcjs = cbfdcjs;
  }

  @Column(name = "gsjs", length = 300)
  public String getGsjs() {
    return this.gsjs;
  }

  public void setGsjs(String gsjs) {
    this.gsjs = gsjs;
  }

  @Column(name = "gsjsr", length = 50)
  public String getGsjsr() {
    return this.gsjsr;
  }

  public void setGsjsr(String gsjsr) {
    this.gsjsr = gsjsr;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "gsshrq", length = 13)
  public Date getGsshrq() {
    return this.gsshrq;
  }

  public void setGsshrq(Date gsshrq) {
    this.gsshrq = gsshrq;
  }

  @Column(name = "gsshr", length = 50)
  public String getGsshr() {
    return this.gsshr;
  }

  public void setGsshr(String gsshr) {
    this.gsshr = gsshr;
  }

  /**
   * @return the orgId
   */
  
  @Column(name = "org_id")
  public long getOrgId() {
    return orgId;
  }

  /**
   * @param orgId the orgId to set
   */
  public void setOrgId(long orgId) {
    this.orgId = orgId;
  }

  /**
   * @return the cbfxb
   */
  
  @Column(name = "cbfxb")
  public char getCbfxb() {
    return cbfxb;
  }

  /**
   * @param cbfxb the cbfxb to set
   */
  public void setCbfxb(char cbfxb) {
    this.cbfxb = cbfxb;
  }

  /**
   * @return the cbfmz
   */
  
  @Column(name = "cbfmz")
  public String getCbfmz() {
    return cbfmz;
  }

  /**
   * @param cbfmz the cbfmz to set
   */
  public void setCbfmz(String cbfmz) {
    this.cbfmz = cbfmz;
  }

}
