package com.mseeworld.qzh.model;
// Generated Aug 20, 2014 8:31:04 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CbfJtcy generated by hbm2java
 */
@Entity
@Table(name="cbf_jtcy"
    ,schema="public"
)
public class CbfJtcy  implements java.io.Serializable {


     private long id;
     private String cbfbm;
     private String cyxm;
     private Character cyxb;
     private Character cyzjlx;
     private String cyzjhm;
     private String yhzgx;
     private Character cybz;
     private Character sfgyr;

    public CbfJtcy() {
    }

	
    public CbfJtcy(long id) {
        this.id = id;
    }
    public CbfJtcy(long id, String cbfbm, String cyxm, Character cyxb, Character cyzjlx, String cyzjhm, String yhzgx, Character cybz, Character sfgyr) {
       this.id = id;
       this.cbfbm = cbfbm;
       this.cyxm = cyxm;
       this.cyxb = cyxb;
       this.cyzjlx = cyzjlx;
       this.cyzjhm = cyzjhm;
       this.yhzgx = yhzgx;
       this.cybz = cybz;
       this.sfgyr = sfgyr;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbfbm", length=18)
    public String getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(String cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="cyxm", length=50)
    public String getCyxm() {
        return this.cyxm;
    }
    
    public void setCyxm(String cyxm) {
        this.cyxm = cyxm;
    }
    
    @Column(name="cyxb", length=1)
    public Character getCyxb() {
        return this.cyxb;
    }
    
    public void setCyxb(Character cyxb) {
        this.cyxb = cyxb;
    }
    
    @Column(name="cyzjlx", length=1)
    public Character getCyzjlx() {
        return this.cyzjlx;
    }
    
    public void setCyzjlx(Character cyzjlx) {
        this.cyzjlx = cyzjlx;
    }
    
    @Column(name="cyzjhm", length=20)
    public String getCyzjhm() {
        return this.cyzjhm;
    }
    
    public void setCyzjhm(String cyzjhm) {
        this.cyzjhm = cyzjhm;
    }
    
    @Column(name="yhzgx", length=2)
    public String getYhzgx() {
        return this.yhzgx;
    }
    
    public void setYhzgx(String yhzgx) {
        this.yhzgx = yhzgx;
    }
    
    @Column(name="cybz", length=1)
    public Character getCybz() {
        return this.cybz;
    }
    
    public void setCybz(Character cybz) {
        this.cybz = cybz;
    }
    
    @Column(name="sfgyr", length=1)
    public Character getSfgyr() {
        return this.sfgyr;
    }
    
    public void setSfgyr(Character sfgyr) {
        this.sfgyr = sfgyr;
    }




}


