package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cbflxdmb generated by hbm2java
 */
@Entity
@Table(name="cbflxdmb"
    ,schema="public"
)
public class Cbflxdmb  implements java.io.Serializable {


     private char dm;
     private String cbflx;

    public Cbflxdmb() {
    }

	
    public Cbflxdmb(char dm) {
        this.dm = dm;
    }
    public Cbflxdmb(char dm, String cbflx) {
       this.dm = dm;
       this.cbflx = cbflx;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=1)
    public char getDm() {
        return this.dm;
    }
    
    public void setDm(char dm) {
        this.dm = dm;
    }
    
    @Column(name="cbflx")
    public String getCbflx() {
        return this.cbflx;
    }
    
    public void setCbflx(String cbflx) {
        this.cbflx = cbflx;
    }




}


