package com.mseeworld.qzh.model;
// Generated Oct 24, 2014 10:26:38 PM by Hibernate Tools 3.2.1.GA

/**
 * Cbht generated by hbm2java
 */
public class Cbht1 implements java.io.Serializable {

  private long id;
  private String cbhtbm;
  private String ycbhtbm;
  private String fbfbm;
  private String cbfbm;
  private String cbfs;
  private String cbqxq;
  private String cbqxz;
  private Float htzmj;
  private Integer cbdkzs;
  private String qdsj;
  private Long orgId;

  public Cbht1() {
  }

  public Cbht1(long id, String cbhtbm) {
    this.id = id;
    this.cbhtbm = cbhtbm;
  }

  public Cbht1(long id, String cbhtbm, String ycbhtbm, String fbfbm, String cbfbm, String cbfs, String cbqxq, String cbqxz, Float htzmj, Integer cbdkzs, String qdsj, long orgId) {
    this.id = id;
    this.cbhtbm = cbhtbm;
    this.ycbhtbm = ycbhtbm;
    this.fbfbm = fbfbm;
    this.cbfbm = cbfbm;
    this.cbfs = cbfs;
    this.cbqxq = cbqxq;
    this.cbqxz = cbqxz;
    this.htzmj = htzmj;
    this.cbdkzs = cbdkzs;
    this.qdsj = qdsj;
    this.orgId = orgId;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getCbhtbm() {
    return this.cbhtbm;
  }

  public void setCbhtbm(String cbhtbm) {
    this.cbhtbm = cbhtbm;
  }

  public String getYcbhtbm() {
    return this.ycbhtbm;
  }

  public void setYcbhtbm(String ycbhtbm) {
    this.ycbhtbm = ycbhtbm;
  }

  public String getFbfbm() {
    return this.fbfbm;
  }

  public void setFbfbm(String fbfbm) {
    this.fbfbm = fbfbm;
  }

  public String getCbfbm() {
    return this.cbfbm;
  }

  public void setCbfbm(String cbfbm) {
    this.cbfbm = cbfbm;
  }

  public String getCbfs() {
    return this.cbfs;
  }

  public void setCbfs(String cbfs) {
    this.cbfs = cbfs;
  }

  public String getCbqxq() {
    return this.cbqxq;
  }

  public void setCbqxq(String cbqxq) {
    this.cbqxq = cbqxq;
  }

  public String getCbqxz() {
    return this.cbqxz;
  }

  public void setCbqxz(String cbqxz) {
    this.cbqxz = cbqxz;
  }

  public Float getHtzmj() {
    return this.htzmj;
  }

  public void setHtzmj(Float htzmj) {
    this.htzmj = htzmj;
  }

  public Integer getCbdkzs() {
    return this.cbdkzs;
  }

  public void setCbdkzs(Integer cbdkzs) {
    this.cbdkzs = cbdkzs;
  }

  public String getQdsj() {
    return this.qdsj;
  }

  public void setQdsj(String qdsj) {
    this.qdsj = qdsj;
  }

  /**
   * @return the orgId
   */
  public Long getOrgId() {
    return orgId;
  }

  /**
   * @param orgId the orgId to set
   */
  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }
}
