package com.mseeworld.qzh.model;
// Generated Aug 20, 2014 8:31:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cbht generated by hbm2java
 */
@Entity
@Table(name="cbht"
    ,schema="public"
)
public class Cbht  implements java.io.Serializable {


     private long id;
     private char cbhtbm;
     private Character ycbhtbm;
     private Character fbfbm;
     private Character cbfbm;
     private Character cbfs;
     private Date cbqxq;
     private Date cbqxz;
     private Float htzmj;
     private Integer cbdkzs;
     private Date qdsj;

    public Cbht() {
    }

	
    public Cbht(long id, char cbhtbm) {
        this.id = id;
        this.cbhtbm = cbhtbm;
    }
    public Cbht(long id, char cbhtbm, Character ycbhtbm, Character fbfbm, Character cbfbm, Character cbfs, Date cbqxq, Date cbqxz, Float htzmj, Integer cbdkzs, Date qdsj) {
       this.id = id;
       this.cbhtbm = cbhtbm;
       this.ycbhtbm = ycbhtbm;
       this.fbfbm = fbfbm;
       this.cbfbm = cbfbm;
       this.cbfs = cbfs;
       this.cbqxq = cbqxq;
       this.cbqxz = cbqxz;
       this.htzmj = htzmj;
       this.cbdkzs = cbdkzs;
       this.qdsj = qdsj;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbhtbm", nullable=false, length=1)
    public char getCbhtbm() {
        return this.cbhtbm;
    }
    
    public void setCbhtbm(char cbhtbm) {
        this.cbhtbm = cbhtbm;
    }
    
    @Column(name="ycbhtbm", length=1)
    public Character getYcbhtbm() {
        return this.ycbhtbm;
    }
    
    public void setYcbhtbm(Character ycbhtbm) {
        this.ycbhtbm = ycbhtbm;
    }
    
    @Column(name="fbfbm", length=1)
    public Character getFbfbm() {
        return this.fbfbm;
    }
    
    public void setFbfbm(Character fbfbm) {
        this.fbfbm = fbfbm;
    }
    
    @Column(name="cbfbm", length=1)
    public Character getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(Character cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="cbfs", length=1)
    public Character getCbfs() {
        return this.cbfs;
    }
    
    public void setCbfs(Character cbfs) {
        this.cbfs = cbfs;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxq", length=13)
    public Date getCbqxq() {
        return this.cbqxq;
    }
    
    public void setCbqxq(Date cbqxq) {
        this.cbqxq = cbqxq;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxz", length=13)
    public Date getCbqxz() {
        return this.cbqxz;
    }
    
    public void setCbqxz(Date cbqxz) {
        this.cbqxz = cbqxz;
    }
    
    @Column(name="htzmj", precision=8, scale=8)
    public Float getHtzmj() {
        return this.htzmj;
    }
    
    public void setHtzmj(Float htzmj) {
        this.htzmj = htzmj;
    }
    
    @Column(name="cbdkzs")
    public Integer getCbdkzs() {
        return this.cbdkzs;
    }
    
    public void setCbdkzs(Integer cbdkzs) {
        this.cbdkzs = cbdkzs;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qdsj", length=13)
    public Date getQdsj() {
        return this.qdsj;
    }
    
    public void setQdsj(Date qdsj) {
        this.qdsj = qdsj;
    }




}


