package com.mseeworld.qzh.model;
// Generated Oct 28, 2014 10:12:26 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cbht generated by hbm2java
 */
@Entity
@Table(name="cbht"
    ,schema="public"
)
public class Cbht  implements java.io.Serializable {


     private long id;
     private String cbhtbm;
     private String ycbhtbm;
     private String fbfbm;
     private String cbfbm;
     private String cbfs;
     private Date cbqxq;
     private Date cbqxz;
     private Float htzmj;
     private Integer cbdkzs;
     private Date qdsj;
     private Long orgId;

    public Cbht() {
    }

	
    public Cbht(long id, String cbhtbm) {
        this.id = id;
        this.cbhtbm = cbhtbm;
    }
    public Cbht(long id, String cbhtbm, String ycbhtbm, String fbfbm, String cbfbm, String cbfs, Date cbqxq, Date cbqxz, Float htzmj, Integer cbdkzs, Date qdsj, Long orgId) {
       this.id = id;
       this.cbhtbm = cbhtbm;
       this.ycbhtbm = ycbhtbm;
       this.fbfbm = fbfbm;
       this.cbfbm = cbfbm;
       this.cbfs = cbfs;
       this.cbqxq = cbqxq;
       this.cbqxz = cbqxz;
       this.htzmj = htzmj;
       this.cbdkzs = cbdkzs;
       this.qdsj = qdsj;
       this.orgId = orgId;
    }
   
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbht_seq")
  @SequenceGenerator(name = "cbht_seq", sequenceName = "cbht_id_seq")
  @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbhtbm", nullable=false, length=19)
    public String getCbhtbm() {
        return this.cbhtbm;
    }
    
    public void setCbhtbm(String cbhtbm) {
        this.cbhtbm = cbhtbm;
    }
    
    @Column(name="ycbhtbm", length=19)
    public String getYcbhtbm() {
        return this.ycbhtbm;
    }
    
    public void setYcbhtbm(String ycbhtbm) {
        this.ycbhtbm = ycbhtbm;
    }
    
    @Column(name="fbfbm", length=14)
    public String getFbfbm() {
        return this.fbfbm;
    }
    
    public void setFbfbm(String fbfbm) {
        this.fbfbm = fbfbm;
    }
    
    @Column(name="cbfbm", length=18)
    public String getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(String cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="cbfs", length=3)
    public String getCbfs() {
        return this.cbfs;
    }
    
    public void setCbfs(String cbfs) {
        this.cbfs = cbfs;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxq", length=13)
    public Date getCbqxq() {
        return this.cbqxq;
    }
    
    public void setCbqxq(Date cbqxq) {
        this.cbqxq = cbqxq;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxz", length=13)
    public Date getCbqxz() {
        return this.cbqxz;
    }
    
    public void setCbqxz(Date cbqxz) {
        this.cbqxz = cbqxz;
    }
    
    @Column(name="htzmj", precision=8, scale=8)
    public Float getHtzmj() {
        return this.htzmj;
    }
    
    public void setHtzmj(Float htzmj) {
        this.htzmj = htzmj;
    }
    
    @Column(name="cbdkzs")
    public Integer getCbdkzs() {
        return this.cbdkzs;
    }
    
    public void setCbdkzs(Integer cbdkzs) {
        this.cbdkzs = cbdkzs;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qdsj", length=13)
    public Date getQdsj() {
        return this.qdsj;
    }
    
    public void setQdsj(Date qdsj) {
        this.qdsj = qdsj;
    }
    
    @Column(name="org_id")
    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }




}


