package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import com.mseeworld.qzh.bean.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cbjyqzdjb2 generated by hbm2java
 */
@Entity
@Table(name="cbjyqzdjb"
    ,schema="public"
)
public class Cbjyqzdjb2  implements java.io.Serializable {


     private long id;
     private String cbjyqzbm;
     private String fbfbm;
     private String cbfbm;
     private String cbfs;
     private String cbqx;
     private Date cbqxq;
     private Date cbqxz;
     private String dksyt;

    public Cbjyqzdjb2() {
    }

	
    public Cbjyqzdjb2(long id) {
        this.id = id;
    }
    public Cbjyqzdjb2(long id, String cbjyqzbm, String fbfbm, String cbfbm, String cbfs, String cbqx, Date cbqxq, Date cbqxz, String dksyt) {
       this.id = id;
       this.cbjyqzbm = cbjyqzbm;
       this.fbfbm = fbfbm;
       this.cbfbm = cbfbm;
       this.cbfs = cbfs;
       this.cbqx = cbqx;
       this.cbqxq = cbqxq;
       this.cbqxz = cbqxz;
       this.dksyt = dksyt;
    }
   
     @Id 
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbjyqzdjb_seq")
  @SequenceGenerator(name = "cbjyqzdjb_seq", sequenceName = "cbjyqzdjb_id_seq",allocationSize=1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbjyqzbm", length=19)
    public String getCbjyqzbm() {
        return this.cbjyqzbm;
    }
    
    public void setCbjyqzbm(String cbjyqzbm) {
        this.cbjyqzbm = cbjyqzbm;
    }
    
    @Column(name="fbfbm", length=14)
    public String getFbfbm() {
        return this.fbfbm;
    }
    
    public void setFbfbm(String fbfbm) {
        this.fbfbm = fbfbm;
    }
    
    @Column(name="cbfbm", length=18)
    public String getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(String cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="cbfs", length=3)
    public String getCbfs() {
        return this.cbfs;
    }
    
    public void setCbfs(String cbfs) {
        this.cbfs = cbfs;
    }
    
    @Column(name="cbqx", length=30)
    public String getCbqx() {
        return this.cbqx;
    }
    
    public void setCbqx(String cbqx) {
        this.cbqx = cbqx;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxq", length=13)
    public Date getCbqxq() {
        return this.cbqxq;
    }
    
    public void setCbqxq(Date cbqxq) {
        this.cbqxq = cbqxq;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="cbqxz", length=13)
    public Date getCbqxz() {
        return this.cbqxz;
    }
    
    public void setCbqxz(Date cbqxz) {
        this.cbqxz = cbqxz;
    }
    
    @Column(name="dksyt")
    public String getDksyt() {
        return this.dksyt;
    }
    
    public void setDksyt(String dksyt) {
        this.dksyt = dksyt;
    }




}


