package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CbjyqzQzhf generated by hbm2java
 */
@Entity
@Table(name="cbjyqz_qzhf"
    ,schema="public"
)
public class CbjyqzQzhf  implements java.io.Serializable {


     private long id;
     private String cbjyqzbm;
     private String qzhfyy;
     private Date hfrq;
     private Date qzhflqrq;
     private String qzhflqrxm;
     private Character hflqrzjlx;
     private String hflqrzjhm;

    public CbjyqzQzhf() {
    }

	
    public CbjyqzQzhf(long id) {
        this.id = id;
    }
    public CbjyqzQzhf(long id, String cbjyqzbm, String qzhfyy, Date hfrq, Date qzhflqrq, String qzhflqrxm, Character hflqrzjlx, String hflqrzjhm) {
       this.id = id;
       this.cbjyqzbm = cbjyqzbm;
       this.qzhfyy = qzhfyy;
       this.hfrq = hfrq;
       this.qzhflqrq = qzhflqrq;
       this.qzhflqrxm = qzhflqrxm;
       this.hflqrzjlx = hflqrzjlx;
       this.hflqrzjhm = hflqrzjhm;
    }
   

     @Id 
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbjyqz_qzhf_seq")
  @SequenceGenerator(name = "cbjyqz_qzhf_seq", sequenceName = "cbjyqz_qzhf_id_seq",allocationSize=1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbjyqzbm", length=19)
    public String getCbjyqzbm() {
        return this.cbjyqzbm;
    }
    
    public void setCbjyqzbm(String cbjyqzbm) {
        this.cbjyqzbm = cbjyqzbm;
    }
    
    @Column(name="qzhfyy", length=200)
    public String getQzhfyy() {
        return this.qzhfyy;
    }
    
    public void setQzhfyy(String qzhfyy) {
        this.qzhfyy = qzhfyy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="hfrq", length=13)
    public Date getHfrq() {
        return this.hfrq;
    }
    
    public void setHfrq(Date hfrq) {
        this.hfrq = hfrq;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qzhflqrq", length=13)
    public Date getQzhflqrq() {
        return this.qzhflqrq;
    }
    
    public void setQzhflqrq(Date qzhflqrq) {
        this.qzhflqrq = qzhflqrq;
    }
    
    @Column(name="qzhflqrxm", length=10)
    public String getQzhflqrxm() {
        return this.qzhflqrxm;
    }
    
    public void setQzhflqrxm(String qzhflqrxm) {
        this.qzhflqrxm = qzhflqrxm;
    }
    
    @Column(name="hflqrzjlx", length=1)
    public Character getHflqrzjlx() {
        return this.hflqrzjlx;
    }
    
    public void setHflqrzjlx(Character hflqrzjlx) {
        this.hflqrzjlx = hflqrzjlx;
    }
    
    @Column(name="hflqrzjhm", length=20)
    public String getHflqrzjhm() {
        return this.hflqrzjhm;
    }
    
    public void setHflqrzjhm(String hflqrzjhm) {
        this.hflqrzjhm = hflqrzjhm;
    }




}


