package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CbjyqzQzzx generated by hbm2java
 */
@Entity
@Table(name="cbjyqz_qzzx"
    ,schema="public"
)
public class CbjyqzQzzx  implements java.io.Serializable {


     private long id;
     private String cbjyqzbm;
     private String zxyy;
     private Date zxrq;

    public CbjyqzQzzx() {
    }

	
    public CbjyqzQzzx(long id) {
        this.id = id;
    }
    public CbjyqzQzzx(long id, String cbjyqzbm, String zxyy, Date zxrq) {
       this.id = id;
       this.cbjyqzbm = cbjyqzbm;
       this.zxyy = zxyy;
       this.zxrq = zxrq;
    }
   

     @Id 
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbjyqz_qzzx_seq")
  @SequenceGenerator(name = "cbjyqz_qzzx_seq", sequenceName = "cbjyqz_qzzx_id_seq")
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbjyqzbm", length=19)
    public String getCbjyqzbm() {
        return this.cbjyqzbm;
    }
    
    public void setCbjyqzbm(String cbjyqzbm) {
        this.cbjyqzbm = cbjyqzbm;
    }
    
    @Column(name="zxyy", length=200)
    public String getZxyy() {
        return this.zxyy;
    }
    
    public void setZxyy(String zxyy) {
        this.zxyy = zxyy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="zxrq", length=13)
    public Date getZxrq() {
        return this.zxrq;
    }
    
    public void setZxrq(Date zxrq) {
        this.zxrq = zxrq;
    }




}


