package com.mseeworld.qzh.model;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cbjyqz generated by hbm2java
 */
@Entity
@Table(name="cbjyqz"
    ,schema="public"
)
public class Cbjyqz  implements java.io.Serializable {


     private long id;
     private String cbjyqzbm;
     private String fzjg;
     private Date fzrq;
     private Character qzsfly;
     private Date qzlqrq;
     private String qzlqrxm;
     private Character qzlqrzjlx;
     private String qzlqrzjhm;

    public Cbjyqz() {
    }

	
    public Cbjyqz(long id) {
        this.id = id;
    }
    public Cbjyqz(long id, String cbjyqzbm, String fzjg, Date fzrq, Character qzsfly, Date qzlqrq, String qzlqrxm, Character qzlqrzjlx, String qzlqrzjhm) {
       this.id = id;
       this.cbjyqzbm = cbjyqzbm;
       this.fzjg = fzjg;
       this.fzrq = fzrq;
       this.qzsfly = qzsfly;
       this.qzlqrq = qzlqrq;
       this.qzlqrxm = qzlqrxm;
       this.qzlqrzjlx = qzlqrzjlx;
       this.qzlqrzjhm = qzlqrzjhm;
    }
   
     @Id 
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbjyqz_seq")
  @SequenceGenerator(name = "cbjyqz_seq", sequenceName = "cbjyqz_id_seq",allocationSize=1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="cbjyqzbm", length=19)
    public String getCbjyqzbm() {
        return this.cbjyqzbm;
    }
    
    public void setCbjyqzbm(String cbjyqzbm) {
        this.cbjyqzbm = cbjyqzbm;
    }
    
    @Column(name="fzjg", length=50)
    public String getFzjg() {
        return this.fzjg;
    }
    
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fzrq", length=13)
    public Date getFzrq() {
        return this.fzrq;
    }
    
    public void setFzrq(Date fzrq) {
        this.fzrq = fzrq;
    }
    
    @Column(name="qzsfly", length=1)
    public Character getQzsfly() {
        return this.qzsfly;
    }
    
    public void setQzsfly(Character qzsfly) {
        this.qzsfly = qzsfly;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qzlqrq", length=13)
    public Date getQzlqrq() {
        return this.qzlqrq;
    }
    
    public void setQzlqrq(Date qzlqrq) {
        this.qzlqrq = qzlqrq;
    }
    
    @Column(name="qzlqrxm", length=10)
    public String getQzlqrxm() {
        return this.qzlqrxm;
    }
    
    public void setQzlqrxm(String qzlqrxm) {
        this.qzlqrxm = qzlqrxm;
    }
    
    @Column(name="qzlqrzjlx", length=1)
    public Character getQzlqrzjlx() {
        return this.qzlqrzjlx;
    }
    
    public void setQzlqrzjlx(Character qzlqrzjlx) {
        this.qzlqrzjlx = qzlqrzjlx;
    }
    
    @Column(name="qzlqrzjhm", length=20)
    public String getQzlqrzjhm() {
        return this.qzlqrzjhm;
    }
    
    public void setQzlqrzjhm(String qzlqrzjhm) {
        this.qzlqrzjhm = qzlqrzjhm;
    }




}


