package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cybzdmb generated by hbm2java
 */
@Entity
@Table(name="cybzdmb"
    ,schema="public"
)
public class Cybzdmb  implements java.io.Serializable {


     private char dm;
     private String cybz;

    public Cybzdmb() {
    }

	
    public Cybzdmb(char dm) {
        this.dm = dm;
    }
    public Cybzdmb(char dm, String cybz) {
       this.dm = dm;
       this.cybz = cybz;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=1)
    public char getDm() {
        return this.dm;
    }
    
    public void setDm(char dm) {
        this.dm = dm;
    }
    
    @Column(name="cybz")
    public String getCybz() {
        return this.cybz;
    }
    
    public void setCybz(String cybz) {
        this.cybz = cybz;
    }




}


