package com.mseeworld.qzh.model;
// Generated Oct 28, 2014 10:14:03 PM by Hibernate Tools 3.2.1.GA


import com.mseeworld.qzh.bean.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Dk2 generated by hbm2java
 */
@Entity
@Table(name="dk"
    ,schema="public"
)
public class Dk2  implements java.io.Serializable {


     private long id;
     private String dkbm;
     private String dkmc;
     private String syqxz;
     private String dklb;
     private String tdlylx;
     private String dldj;
     private Character tdyt;
     private Character sfjbnt;
     private Float scmj;
     private String dkdz;
     private String dkxz;
     private String dknz;
     private String dkbz;
     private String dkbzxx;
     private String zjrxm;
     private Long orgId;
     private Long cbhtId;
  private String orgName;

    public Dk2() {
    }

	
    public Dk2(long id) {
        this.id = id;
    }
    public Dk2(long id, String dkbm, String dkmc, String syqxz, String dklb, String tdlylx, String dldj, Character tdyt, Character sfjbnt, Float scmj, String dkdz, String dkxz, String dknz, String dkbz, String dkbzxx, String zjrxm, Long orgId, Long cbhtId) {
       this.id = id;
       this.dkbm = dkbm;
       this.dkmc = dkmc;
       this.syqxz = syqxz;
       this.dklb = dklb;
       this.tdlylx = tdlylx;
       this.dldj = dldj;
       this.tdyt = tdyt;
       this.sfjbnt = sfjbnt;
       this.scmj = scmj;
       this.dkdz = dkdz;
       this.dkxz = dkxz;
       this.dknz = dknz;
       this.dkbz = dkbz;
       this.dkbzxx = dkbzxx;
       this.zjrxm = zjrxm;
       this.orgId = orgId;
       this.cbhtId = cbhtId;
    }
    
     @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "dk_seq")
  @SequenceGenerator(name = "dk_seq", sequenceName = "dk_id_seq",allocationSize=1)
  @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="dkbm", length=22)
    public String getDkbm() {
        return this.dkbm;
    }
    
    public void setDkbm(String dkbm) {
        this.dkbm = dkbm;
    }
    
    @Column(name="dkmc", length=50)
    public String getDkmc() {
        return this.dkmc;
    }
    
    public void setDkmc(String dkmc) {
        this.dkmc = dkmc;
    }
    
    @Column(name="syqxz", length=2)
    public String getSyqxz() {
        return this.syqxz;
    }
    
    public void setSyqxz(String syqxz) {
        this.syqxz = syqxz;
    }
    
    @Column(name="dklb", length=2)
    public String getDklb() {
        return this.dklb;
    }
    
    public void setDklb(String dklb) {
        this.dklb = dklb;
    }
    
    @Column(name="tdlylx", length=3)
    public String getTdlylx() {
        return this.tdlylx;
    }
    
    public void setTdlylx(String tdlylx) {
        this.tdlylx = tdlylx;
    }
    
    @Column(name="dldj", length=2)
    public String getDldj() {
        return this.dldj;
    }
    
    public void setDldj(String dldj) {
        this.dldj = dldj;
    }
    
    @Column(name="tdyt", length=1)
    public Character getTdyt() {
        return this.tdyt;
    }
    
    public void setTdyt(Character tdyt) {
        this.tdyt = tdyt;
    }
    
    @Column(name="sfjbnt", length=1)
    public Character getSfjbnt() {
        return this.sfjbnt;
    }
    
    public void setSfjbnt(Character sfjbnt) {
        this.sfjbnt = sfjbnt;
    }
    
    @Column(name="scmj", precision=8, scale=8)
    public Float getScmj() {
        return this.scmj;
    }
    
    public void setScmj(Float scmj) {
        this.scmj = scmj;
    }
    
    @Column(name="dkdz", length=50)
    public String getDkdz() {
        return this.dkdz;
    }
    
    public void setDkdz(String dkdz) {
        this.dkdz = dkdz;
    }
    
    @Column(name="dkxz", length=50)
    public String getDkxz() {
        return this.dkxz;
    }
    
    public void setDkxz(String dkxz) {
        this.dkxz = dkxz;
    }
    
    @Column(name="dknz", length=50)
    public String getDknz() {
        return this.dknz;
    }
    
    public void setDknz(String dknz) {
        this.dknz = dknz;
    }
    
    @Column(name="dkbz", length=50)
    public String getDkbz() {
        return this.dkbz;
    }
    
    public void setDkbz(String dkbz) {
        this.dkbz = dkbz;
    }
    
    @Column(name="dkbzxx", length=300)
    public String getDkbzxx() {
        return this.dkbzxx;
    }
    
    public void setDkbzxx(String dkbzxx) {
        this.dkbzxx = dkbzxx;
    }
    
    @Column(name="zjrxm", length=100)
    public String getZjrxm() {
        return this.zjrxm;
    }
    
    public void setZjrxm(String zjrxm) {
        this.zjrxm = zjrxm;
    }
    
    @Column(name="org_id")
    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
    
    @Column(name="cbht_id")
    public Long getCbhtId() {
        return this.cbhtId;
    }
    
    public void setCbhtId(Long cbhtId) {
        this.cbhtId = cbhtId;
    }



  /**
   * @return the orgName
   */
  @Column(name = "org_name")
  public String getOrgName() {
    return orgName;
  }

  /**
   * @param orgName the orgName to set
   */
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


}


