package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dklbdmb generated by hbm2java
 */
@Entity
@Table(name="dklbdmb"
    ,schema="public"
)
public class Dklbdmb  implements java.io.Serializable {


     private String dm;
     private String dkxz;

    public Dklbdmb() {
    }

	
    public Dklbdmb(String dm) {
        this.dm = dm;
    }
    public Dklbdmb(String dm, String dkxz) {
       this.dm = dm;
       this.dkxz = dkxz;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=2)
    public String getDm() {
        return this.dm;
    }
    
    public void setDm(String dm) {
        this.dm = dm;
    }
    
    @Column(name="dkxz")
    public String getDkxz() {
        return this.dkxz;
    }
    
    public void setDkxz(String dkxz) {
        this.dkxz = dkxz;
    }




}


