package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dldjdmb generated by hbm2java
 */
@Entity
@Table(name="dldjdmb"
    ,schema="public"
)
public class Dldjdmb  implements java.io.Serializable {


     private String dm;
     private String dldj;

    public Dldjdmb() {
    }

	
    public Dldjdmb(String dm) {
        this.dm = dm;
    }
    public Dldjdmb(String dm, String dldj) {
       this.dm = dm;
       this.dldj = dldj;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=2)
    public String getDm() {
        return this.dm;
    }
    
    public void setDm(String dm) {
        this.dm = dm;
    }
    
    @Column(name="dldj")
    public String getDldj() {
        return this.dldj;
    }
    
    public void setDldj(String dldj) {
        this.dldj = dldj;
    }




}


