package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tdytdmb generated by hbm2java
 */
@Entity
@Table(name="tdytdmb"
    ,schema="public"
)
public class Tdytdmb  implements java.io.Serializable {


     private char dm;
     private String tdytd;

    public Tdytdmb() {
    }

	
    public Tdytdmb(char dm) {
        this.dm = dm;
    }
    public Tdytdmb(char dm, String tdytd) {
       this.dm = dm;
       this.tdytd = tdytd;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=1)
    public char getDm() {
        return this.dm;
    }
    
    public void setDm(char dm) {
        this.dm = dm;
    }
    
    @Column(name="tdytd")
    public String getTdytd() {
        return this.tdytd;
    }
    
    public void setTdytd(String tdytd) {
        this.tdytd = tdytd;
    }




}


