package com.mseeworld.qzh.model;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zjlxdmb generated by hbm2java
 */
@Entity
@Table(name="zjlxdmb"
    ,schema="public"
)
public class Zjlxdmb  implements java.io.Serializable {


     private char dm;
     private String zjlx;

    public Zjlxdmb() {
    }

	
    public Zjlxdmb(char dm) {
        this.dm = dm;
    }
    public Zjlxdmb(char dm, String zjlx) {
       this.dm = dm;
       this.zjlx = zjlx;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=1)
    public char getDm() {
        return this.dm;
    }
    
    public void setDm(char dm) {
        this.dm = dm;
    }
    
    @Column(name="zjlx")
    public String getZjlx() {
        return this.zjlx;
    }
    
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx;
    }




}


