/*
 *  
 */
 Ext.define("core.user.model.UserModel",{
 	extend:"Ext.data.Model",
 	fields:[
 		{name:"id",type:"int",srotable:false},
 		{name:"name",type:"string",srotable:false},
 		{name:"orgName",type:"string",srotable:false}
 	]
 });