/*
 *  
 */
 Ext.define("core.cbht.store.FbfStore",{
 	extend:'Ext.data.Store',
	model:'core.fbf.model.FbfModel',
	pageSize:10,
	//autoSync:true,//与服务器同步
	proxy:{
		type:"ajax",
		url:"./people/listall_people.do",
		reader:{
			type:"json",
			root:"rows",
			totalProperty :'totalCount'		
		},
		writer:{
			type:"json"
		}
	},
	autoLoad:true	
 });