Ext.define("core.user.view.UserForm", {
  extend: "Ext.form.Panel",
  alias: "widget.userform",
  align: "left",
  frame: true,
  defaults: {
    margin: "7 0 0 15",
    selectOnFocus: true
  },
  layout: {
    type: "table",
    columns: 1
  },
  tbar: [{
      xtype: "button",
      ref: "save",
      iconCls: 'table_save',
      text: "保存"
    }],
  items: [{
      xtype: "textfield",
      fieldLabel: "所属区域",
      name: "orgName",
      allowBlank: true,
      blankText: '必须在右侧选择村级以下区域',
      readOnly: true
    }, {
      xtype: "textfield",
      fieldLabel: "区域级别",
      name: "isAdd",
      value: "1",
      hidden: true
    }, {
      xtype: "textfield",
      fieldLabel: "区域级别",
      name: "orgLevel",
      value: "0",
      hidden: true
    }, {
      xtype: "textfield",
      fieldLabel: "主键",
      name: "id",
      value: "",
      hidden: true
    }, {
      xtype: "textfield",
      fieldLabel: "组织机构id",
      name: "orgId",
      value: "",
      hidden: true
    }, {
      xtype: "textfield",
      fieldLabel: "用户名",
      name: "userbm",
      allowBlank: false,
      blankText: '发包方编码不能为空'
    }, {
      xtype: "textfield",
      fieldLabel: "密码",
      name: "usermc",
      allowBlank: false,
      blankText: '发包方名称不能为空',
      readOnly: false
    }, {
      xtype: "textfield",
      fieldLabel: "再次输入密码",
      name: "userfzrxm",
      readOnly: false
    }]
});