package com.mseeworld.qzh.bean;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cbdkxx generated by hbm2java
 */
@Entity
@Table(name="cbdkxx"
    ,schema="public"
)
public class Cbdkxx  implements java.io.Serializable {


     private long id;
     private String dkbm;
     private String fbfbm;
     private String cbfbm;
     private String cbjyqqdfs;
     private Float htmj;
     private String cbhtbm;
     private String lzhtbm;
     private String cbjyqzbm;

    public Cbdkxx() {
    }

	
    public Cbdkxx(long id) {
        this.id = id;
    }
    public Cbdkxx(long id, String dkbm, String fbfbm, String cbfbm, String cbjyqqdfs, Float htmj, String cbhtbm, String lzhtbm, String cbjyqzbm) {
       this.id = id;
       this.dkbm = dkbm;
       this.fbfbm = fbfbm;
       this.cbfbm = cbfbm;
       this.cbjyqqdfs = cbjyqqdfs;
       this.htmj = htmj;
       this.cbhtbm = cbhtbm;
       this.lzhtbm = lzhtbm;
       this.cbjyqzbm = cbjyqzbm;
    }
   
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cbdkxx_seq")
  @SequenceGenerator(name = "cbdkxx_seq", sequenceName = "cbdkxx_id_seq",allocationSize=1)
  @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="dkbm", length=22)
    public String getDkbm() {
        return this.dkbm;
    }
    
    public void setDkbm(String dkbm) {
        this.dkbm = dkbm;
    }
    
    @Column(name="fbfbm", length=14)
    public String getFbfbm() {
        return this.fbfbm;
    }
    
    public void setFbfbm(String fbfbm) {
        this.fbfbm = fbfbm;
    }
    
    @Column(name="cbfbm", length=18)
    public String getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(String cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="cbjyqqdfs", length=3)
    public String getCbjyqqdfs() {
        return this.cbjyqqdfs;
    }
    
    public void setCbjyqqdfs(String cbjyqqdfs) {
        this.cbjyqqdfs = cbjyqqdfs;
    }
    
    @Column(name="htmj", precision=8, scale=8)
    public Float getHtmj() {
        return this.htmj;
    }
    
    public void setHtmj(Float htmj) {
        this.htmj = htmj;
    }
    
    @Column(name="cbhtbm", length=18)
    public String getCbhtbm() {
        return this.cbhtbm;
    }
    
    public void setCbhtbm(String cbhtbm) {
        this.cbhtbm = cbhtbm;
    }
    
    @Column(name="lzhtbm", length=20)
    public String getLzhtbm() {
        return this.lzhtbm;
    }
    
    public void setLzhtbm(String lzhtbm) {
        this.lzhtbm = lzhtbm;
    }
    
    @Column(name="cbjyqzbm", length=19)
    public String getCbjyqzbm() {
        return this.cbjyqzbm;
    }
    
    public void setCbjyqzbm(String cbjyqzbm) {
        this.cbjyqzbm = cbjyqzbm;
    }




}


