package com.mseeworld.qzh.bean;
// Generated Sep 6, 2014 9:23:12 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Lzht generated by hbm2java
 */
@Entity
@Table(name="lzht"
    ,schema="public"
)
public class Lzht1  implements java.io.Serializable {


     private long id;
     private String ycbhtbm;
     private String lzhtbm;
     private String cbfbm;
     private String srfbm;
     private String lzfs;
     private String lzqx;
     private String lzqxksrq;
     private String lzqxjsrq;
     private Float lzmj;
     private Integer lzdks;
     private String lzqtdyt;
     private String lzhtdyt;
     private String lzjgsm;
     private String htqdrq;
     private Long orgId;

    public Lzht1() {
    }

	
    public Lzht1(long id) {
        this.id = id;
    }
    public Lzht1(long id, String ycbhtbm, String lzhtbm, String cbfbm, String srfbm, String lzfs, String lzqx, String lzqxksrq, String lzqxjsrq, Float lzmj, Integer lzdks, String lzqtdyt, String lzhtdyt, String lzjgsm, String htqdrq, Long orgId) {
       this.id = id;
       this.ycbhtbm = ycbhtbm;
       this.lzhtbm = lzhtbm;
       this.cbfbm = cbfbm;
       this.srfbm = srfbm;
       this.lzfs = lzfs;
       this.lzqx = lzqx;
       this.lzqxksrq = lzqxksrq;
       this.lzqxjsrq = lzqxjsrq;
       this.lzmj = lzmj;
       this.lzdks = lzdks;
       this.lzqtdyt = lzqtdyt;
       this.lzhtdyt = lzhtdyt;
       this.lzjgsm = lzjgsm;
       this.htqdrq = htqdrq;
       this.orgId =  orgId;
    }
   
     @Id 
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lzht_seq")
  @SequenceGenerator(name = "lzht_seq", sequenceName = "lzht_id_seq",allocationSize=1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="ycbhtbm", length=19)
    public String getYcbhtbm() {
        return this.ycbhtbm;
    }
    
    public void setYcbhtbm(String ycbhtbm) {
        this.ycbhtbm = ycbhtbm;
    }
    
    @Column(name="lzhtbm", length=18)
    public String getLzhtbm() {
        return this.lzhtbm;
    }
    
    public void setLzhtbm(String lzhtbm) {
        this.lzhtbm = lzhtbm;
    }
    
    @Column(name="cbfbm", length=18)
    public String getCbfbm() {
        return this.cbfbm;
    }
    
    public void setCbfbm(String cbfbm) {
        this.cbfbm = cbfbm;
    }
    
    @Column(name="srfbm", length=18)
    public String getSrfbm() {
        return this.srfbm;
    }
    
    public void setSrfbm(String srfbm) {
        this.srfbm = srfbm;
    }
    
    @Column(name="lzfs", length=3)
    public String getLzfs() {
        return this.lzfs;
    }
    
    public void setLzfs(String lzfs) {
        this.lzfs = lzfs;
    }
    
    @Column(name="lzqx", length=10)
    public String getLzqx() {
        return this.lzqx;
    }
    
    public void setLzqx(String lzqx) {
        this.lzqx = lzqx;
    }
    
    @Column(name="lzqxksrq", length=13)
    public String getLzqxksrq() {
        return this.lzqxksrq;
    }
    
    public void setLzqxksrq(String lzqxksrq) {
        this.lzqxksrq = lzqxksrq;
    }
    
    @Column(name="lzqxjsrq", length=13)
    public String getLzqxjsrq() {
        return this.lzqxjsrq;
    }
    
    public void setLzqxjsrq(String lzqxjsrq) {
        this.lzqxjsrq = lzqxjsrq;
    }
    
    @Column(name="lzmj", precision=8, scale=8)
    public Float getLzmj() {
        return this.lzmj;
    }
    
    public void setLzmj(Float lzmj) {
        this.lzmj = lzmj;
    }
    
    @Column(name="lzdks")
    public Integer getLzdks() {
        return this.lzdks;
    }
    
    public void setLzdks(Integer lzdks) {
        this.lzdks = lzdks;
    }
    
    @Column(name="lzqtdyt", length=1)
    public String getLzqtdyt() {
        return this.lzqtdyt;
    }
    
    public void setLzqtdyt(String lzqtdyt) {
        this.lzqtdyt = lzqtdyt;
    }
    
    @Column(name="lzhtdyt", length=1)
    public String getLzhtdyt() {
        return this.lzhtdyt;
    }
    
    public void setLzhtdyt(String lzhtdyt) {
        this.lzhtdyt = lzhtdyt;
    }
    
    @Column(name="lzjgsm", length=100)
    public String getLzjgsm() {
        return this.lzjgsm;
    }
    
    public void setLzjgsm(String lzjgsm) {
        this.lzjgsm = lzjgsm;
    }
    
    @Column(name="htqdrq", length=13)
    public String getHtqdrq() {
        return this.htqdrq;
    }
    
    public void setHtqdrq(String htqdrq) {
        this.htqdrq = htqdrq;
    }

  /**
   * @return the orgId
   */
  public Long getOrgId() {
    return orgId;
  }

  /**
   * @param orgId the orgId to set
   */
  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }




}


