package com.mseeworld.qzh.bean;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Syqsxdmb generated by hbm2java
 */
@Entity
@Table(name="syqsxdmb"
    ,schema="public"
)
public class Syqsxdmb  implements java.io.Serializable {


     private String dm;
     private String syqsx;

    public Syqsxdmb() {
    }

	
    public Syqsxdmb(String dm) {
        this.dm = dm;
    }
    public Syqsxdmb(String dm, String syqsx) {
       this.dm = dm;
       this.syqsx = syqsx;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=2)
    public String getDm() {
        return this.dm;
    }
    
    public void setDm(String dm) {
        this.dm = dm;
    }
    
    @Column(name="syqsx")
    public String getSyqsx() {
        return this.syqsx;
    }
    
    public void setSyqsx(String syqsx) {
        this.syqsx = syqsx;
    }




}


