package com.mseeworld.qzh.bean;
// Generated Jan 2, 2015 1:00:04 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Xbdmb generated by hbm2java
 */
@Entity
@Table(name="xbdmb"
    ,schema="public"
)
public class Xbdmb  implements java.io.Serializable {


     private char dm;
     private String xb;

    public Xbdmb() {
    }

	
    public Xbdmb(char dm) {
        this.dm = dm;
    }
    public Xbdmb(char dm, String xb) {
       this.dm = dm;
       this.xb = xb;
    }
   
     @Id 
    
    @Column(name="dm", unique=true, nullable=false, length=1)
    public char getDm() {
        return this.dm;
    }
    
    public void setDm(char dm) {
        this.dm = dm;
    }
    
    @Column(name="xb")
    public String getXb() {
        return this.xb;
    }
    
    public void setXb(String xb) {
        this.xb = xb;
    }




}


